import { VolcanoData } from './types';

export const INDONESIA_VOLCANOES: VolcanoData[] = [
  {
    id: 'anak-krakatau',
    name: 'Gunung Anak Krakatau',
    regionalLocation: 'Selat Sunda, Lampung - Banten',
    latitude: -6.102,
    longitude: 105.423,
    elevationMeters: 157,
    craterName: 'Kawah Aktif Anak Krakatau',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 5.0,
    columnHeightMeters: 1800,
    lastEruptionDate: '2026-08-28 07:45 WIB',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Abu vulkanik teramati membubung hingga ketinggian 2.000 meter di atas permukaan laut. Sebaran abu melayang mengikuti pola angin troposfer Selat Sunda.',
    description: 'Gunung api aktif tipe kaldera/pulau vulkanik di Selat Sunda. Sering menghasilkan kolom abu vulkanik abu-abu hingga hitam pekat dengan ancaman lontaran material pijar dan hujan abu ke wilayah pesisir Banten dan Lampung Selatan.',
    monitoringPost: 'Pos Pengamatan Gunungapi Pasauran, Serang, Banten'
  },
  {
    id: 'merapi',
    name: 'Gunung Merapi',
    regionalLocation: 'D.I. Yogyakarta & Jawa Tengah',
    latitude: -7.540,
    longitude: 110.446,
    elevationMeters: 2968,
    craterName: 'Kawah Puncak Merapi',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 7.0,
    columnHeightMeters: 2200,
    lastEruptionDate: '2026-08-15 14:20 WIB',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Awan panas guguran teramati ke arah barat daya (Kali Bebeng dan Kali Krasak). Sebaran abu vulkanik terbawa angin ke arah timur dan tenggara.',
    description: 'Gunung api strato aktif tipe eksplosif-efusif dengan kubah lava aktif. Terkenal dengan fenomena Awan Panas Guguran (Wedhus Gembel) yang mengancam lereng selatan dan barat daya.',
    monitoringPost: 'Balai Penyelidikan dan Pengembangan Teknologi Kebencanaan Geologi (BPPTKG) Yogyakarta'
  },
  {
    id: 'semeru',
    name: 'Gunung Semeru (Mahameru)',
    regionalLocation: 'Lumajang & Malang, Jawa Timur',
    latitude: -8.108,
    longitude: 112.922,
    elevationMeters: 3676,
    craterName: 'Kawah Jonggring Saloko',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 5.0,
    columnHeightMeters: 1500,
    lastEruptionDate: '2026-09-02 06:12 WIB',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Erupsi strombolian berkala dengan kolom asap putih kelabu membubung 800 - 1.500m dari kawah Jonggring Saloko. Abu terbawa angin ke arah barat daya.',
    description: 'Puncak tertinggi di Pulau Jawa dengan aktivitas vulkanik harian berupa letusan tipe Vulkanian dan aliran lahar dingin di sepanjang aliran Besuk Kobokan.',
    monitoringPost: 'Pos Pengamatan Gunungapi Semeru, Gunung Sawur, Lumajang'
  },
  {
    id: 'lewotobi-lakilaki',
    name: 'Gunung Lewotobi Laki-laki',
    regionalLocation: 'Flores Timur, Nusa Tenggara Timur',
    latitude: -8.538,
    longitude: 122.768,
    elevationMeters: 1584,
    craterName: 'Kawah Pusat Lewotobi Laki-laki',
    statusLevel: 4,
    statusText: 'AWAS',
    krbRadiusKm: 7.0,
    columnHeightMeters: 3500,
    lastEruptionDate: '2026-09-05 11:30 WITA',
    vonaColorCode: 'RED',
    aviationSummary: 'Kolom erupsi masif mencapai 3.500 meter di atas puncak. Hujan abu tebal terpantau melanda bandara Frans Seda Maumere dan permukiman sekitar Wulanggitang.',
    description: 'Gunung api kembar di Flores Timur yang sedang mengalami peningkatan fase erupsi eksplosif tinggi dengan lontaran batu dan hujan abu vulkanik lebat.',
    monitoringPost: 'Pos Pengamatan Gunungapi Lewotobi Laki-laki, Pululera, Wulanggitang'
  },
  {
    id: 'marapi',
    name: 'Gunung Marapi',
    regionalLocation: 'Agam & Tanah Datar, Sumatera Barat',
    latitude: -0.381,
    longitude: 100.473,
    elevationMeters: 2891,
    craterName: 'Kawah Verbeek',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 4.5,
    columnHeightMeters: 1600,
    lastEruptionDate: '2026-08-30 16:45 WIB',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Kolom abu vulkanik teramati berwarna kelabu hingga hitam membubung setinggi 1.600 meter condong ke arah timur laut.',
    description: 'Gunung api kompleks paling aktif di Sumatera Barat dengan letusan freatik dan magmatik berulang tanpa tanda precursor seismik yang panjang.',
    monitoringPost: 'Pos Pengamatan Gunungapi Marapi, Bukittinggi, Sumatera Barat'
  },
  {
    id: 'ruang',
    name: 'Gunung Ruang',
    regionalLocation: 'Sitaro, Sulawesi Utara',
    latitude: 2.303,
    longitude: 125.367,
    elevationMeters: 725,
    craterName: 'Kawah Puncak Ruang',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 4.0,
    columnHeightMeters: 2500,
    lastEruptionDate: '2026-07-22 09:10 WITA',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Aktivitas kegempaan vulkanik dalam masih terekam tinggi. Emisi asap dan gas belerang tebal terpantau menyebar di perairan Laut Sulawesi.',
    description: 'Pulau gunung api stratovolcano di Kepulauan Sangihe yang berpotensi memicu gelombang tsunami bila terjadi keruntuhan dinding kawah ke laut.',
    monitoringPost: 'Pos PGA Ruang, Tagulandang, Kep. Sitaro'
  },
  {
    id: 'ibu',
    name: 'Gunung Ibu',
    regionalLocation: 'Halmahera Barat, Maluku Utara',
    latitude: 1.488,
    longitude: 127.633,
    elevationMeters: 1325,
    craterName: 'Kawah Puncak Ibu',
    statusLevel: 3,
    statusText: 'SIAGA',
    krbRadiusKm: 5.0,
    columnHeightMeters: 2000,
    lastEruptionDate: '2026-09-06 18:20 WIT',
    vonaColorCode: 'ORANGE',
    aviationSummary: 'Erupsi menerus dengan dentuman kuat dan lontaran lava pijar hingga 1.000 meter ke arah utara dan barat laut.',
    description: 'Gunung api aktif di Halmahera dengan kubah lava di kawah bagian dalam dan frekuensi letusan harian yang sangat intensif.',
    monitoringPost: 'Pos Pengamatan Gunungapi Ibu, Gam Ici, Ibu, Halmahera Barat'
  },
  {
    id: 'sinabung',
    name: 'Gunung Sinabung',
    regionalLocation: 'Karo, Sumatera Utara',
    latitude: 3.170,
    longitude: 98.392,
    elevationMeters: 2460,
    craterName: 'Kawah Sinabung',
    statusLevel: 2,
    statusText: 'WASPADA',
    krbRadiusKm: 3.0,
    columnHeightMeters: 1000,
    lastEruptionDate: '2026-05-14 08:30 WIB',
    vonaColorCode: 'YELLOW',
    aviationSummary: 'Emisi asap kawah bertekanan lemah hingga sedang berwarna putih dengan intensitas tipis hingga sedang.',
    description: 'Gunung api strato di Dataran Tinggi Karo yang kembali aktif sejak 2010 setelah tidur selama lebih dari 400 tahun.',
    monitoringPost: 'Pos Pengamatan Gunungapi Sinabung, Ndokum Siroga, Simpang Empat, Karo'
  }
];

export const PRESET_CITIES = [
  { name: 'Bogor', province: 'Jawa Barat', lat: -6.596356, lon: 106.797319, type: 'Kota' },
  { name: 'Bandar Lampung', province: 'Lampung', lat: -5.429741, lon: 105.262520, type: 'Kota' },
  { name: 'Cilegon', province: 'Banten', lat: -6.017399, lon: 106.053818, type: 'Kota' },
  { name: 'Serang', province: 'Banten', lat: -6.110375, lon: 106.163986, type: 'Kota' },
  { name: 'Anyer (Kecamatan)', province: 'Serang, Banten', lat: -6.052600, lon: 105.929800, type: 'Kecamatan' },
  { name: 'Kalianda (Kecamatan)', province: 'Lampung Selatan', lat: -5.733500, lon: 105.591200, type: 'Kecamatan' },
  { name: 'Pandeglang', province: 'Banten', lat: -6.308800, lon: 106.106500, type: 'Kabupaten' },
  { name: 'Jakarta Pusat', province: 'DKI Jakarta', lat: -6.175392, lon: 106.827153, type: 'Kota' },
  { name: 'Tangerang', province: 'Banten', lat: -6.178306, lon: 106.631889, type: 'Kota' },
  { name: 'Depok', province: 'Jawa Barat', lat: -6.402484, lon: 106.794241, type: 'Kota' },
  { name: 'Bekasi', province: 'Jawa Barat', lat: -6.238270, lon: 106.975571, type: 'Kota' },
  { name: 'Sukabumi', province: 'Jawa Barat', lat: -6.927725, lon: 106.929886, type: 'Kota' },
  { name: 'Yogyakarta', province: 'D.I. Yogyakarta', lat: -7.795580, lon: 110.369490, type: 'Kota' },
  { name: 'Sleman', province: 'D.I. Yogyakarta', lat: -7.688300, lon: 110.339600, type: 'Kabupaten' },
  { name: 'Magelang', province: 'Jawa Tengah', lat: -7.470500, lon: 110.217800, type: 'Kota' },
  { name: 'Boyolali', province: 'Jawa Tengah', lat: -7.536100, lon: 110.594400, type: 'Kabupaten' },
  { name: 'Klaten', province: 'Jawa Tengah', lat: -7.705600, lon: 110.604400, type: 'Kabupaten' },
  { name: 'Malang', province: 'Jawa Timur', lat: -7.979700, lon: 112.630400, type: 'Kota' },
  { name: 'Lumajang', province: 'Jawa Timur', lat: -8.133300, lon: 113.216700, type: 'Kabupaten' },
  { name: 'Maumere', province: 'Nusa Tenggara Timur', lat: -8.620000, lon: 122.210000, type: 'Kota' },
  { name: 'Larantuka', province: 'Flores Timur, NTT', lat: -8.341700, lon: 122.983300, type: 'Kecamatan' },
  { name: 'Bukittinggi', province: 'Sumatera Barat', lat: -0.305500, lon: 100.369200, type: 'Kota' },
  { name: 'Padang Panjang', province: 'Sumatera Barat', lat: -0.463600, lon: 100.398600, type: 'Kota' }
];
